### PR TITLE
Set up CI

### PR DESCRIPTION
**Pull request by dtan4**
## WHAT

Add test script and set up wercker to run CI.
It checks whether the Terraform version used in Docker Image is equal to the expected version.

### CODE REVIEW

**Comment by spesnova** [comment]
I'd like to see build detail on wercker :eyes: 
Please add me to collaborator :wolf:

**Comment by dtan4** [comment]
Sorry, just added! 
Please check again :bow:

**Comment by spesnova** [comment]
[LGTM](http://lgtm.in/i/Ikvr4yRWp)

**Comment by dtan4** [comment]
Finally I made [CI result](https://app.wercker.com/#applications/5541c7f4771355eb400057fe/tab/builds) public... :open_hands:

**Pull request merged**
